// Package main is auto-generated by metricsgen. DO NOT EDIT.
package main

type MetricInfo struct {
	*MetricBpfTcpRx
	*MetricBpfTcpTx
}

//MetricBpfTcpRx TCP received bytes
type MetricBpfTcpRx struct {
}
//MetricBpfTcpTx TCP transmitted bytes
type MetricBpfTcpTx struct {
}

type MetricBpfTcpRxAttributes struct {
	Pid string
}
type MetricBpfTcpTxAttributes struct {
	Pid string
	PidGid string
}
